### ISSUE TITLE
UnsupportedClassVersionError error in Docker image

### ISSUE THREAD

**Issue by gamefundas** [GreenCom-Networks/Franz-manager-api#5]
Getting the following error when running the docker image

docker run -e JVM_HEAP_SIZE=512 -e KAFKA_BROKERS="YOUR_KAFKA_BROKERS_STRING" -e KAFKA_BROKERS_JMX="YOUR_KAFKA_BROKERS_JMX" -p 1337:1337 greencomnetworks/franz-manager-api

Any chance the API was compiled using Java 9 and the image uses Java 8

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/logging/log4j/util/StackLocator has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by lgaillard** [comment]
No tag was set for the maven layer, which meant no jdk version was set.
Recently maven moved from a default jdk8 to jdk11 in preparation for the end of the LTS.

I set the maven version to jdk11 and the release target to jdk8.
In the near future, we'll upgrade the runtime to jdk11.

The fix is available in _master_, and on the _latest_ dockerhub tag.
A new release was also created under version _1.1_.

Sorry for the inconvenience.

**Comment by gamefundas** [comment]
@lgaillard this is a fantastic tool. I managed to get it running.

For a long time we have been using Kafka manager but it has its nuances. Its kind of outdated in way. Franz looks great, the community will love this. Thanks for all the effort.

Any sort of upcoming features or roadmap you have in mind?

**Comment by gamefundas** [comment]
Docker version continues to give an error. It appears "org/apache/logging/log4j/util/StackLocator" has been compiled in more recent java version. Perhaps switching the Docker image to use JDK 11 will make this work.

docker run -e JVM_HEAP_SIZE=512 -e KAFKA_BROKERS="YOUR_KAFKA_BROKERS_STRING" -e KAFKA_BROKERS_JMX="YOUR_KAFKA_BROKERS_JMX" -p 1337:1337 greencomnetworks/franz-manager-api
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/logging/log4j/util/StackLocator has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.apache.logging.log4j.util.StackLocatorUtil.<clinit>(StackLocatorUtil.java:28)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:42)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
        at com.greencomnetworks.franzmanager.FranzManagerApi.<clinit>(FranzManagerApi.java:26)

**Comment by lgaillard** [comment]
Have you tried to pull the layer again?

$ docker pull greencomnetworks/franz-manager-api
$ docker run -e KAFKA_CONF='[]' -p 1337:1337 -p 5443:5443 greencomnetworks/franz-manager-api

**Comment by gamefundas** [comment]
Deleting the image worked fine. Awesome thanks.
